version: "3.8"

name: wallet-app

services:
  app:
    container_name: api_service
    build:
      context: ..
      dockerfile: ./docker/develop.Dockerfile
    env_file:
      - ../.env
    volumes:
      - ..:/app
    ports:
      - "3000:3000"
    networks:
      - wallet-network

  postgres:
    image: postgres:17.2
    container_name: postgres_service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: wallet
    ports:
      - "5432:5432"
    networks:
      - wallet-network

  redis:
    image: redis:7.2-alpine
    container_name: redis_service
    ports:
      - "6379:6379"
    networks:
      - wallet-network

networks:
  wallet-network:
    driver: bridge
